package com.wedding.john.oa.bean;

public class Cameraman {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cameraman.id
     *
     * @mbggenerated Thu Jul 03 17:15:48 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cameraman.name
     *
     * @mbggenerated Thu Jul 03 17:15:48 CST 2014
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cameraman.tel
     *
     * @mbggenerated Thu Jul 03 17:15:48 CST 2014
     */
    private String tel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cameraman.mail
     *
     * @mbggenerated Thu Jul 03 17:15:48 CST 2014
     */
    private String mail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cameraman.camera_type
     *
     * @mbggenerated Thu Jul 03 17:15:48 CST 2014
     */
    private String cameraType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cameraman.level
     *
     * @mbggenerated Thu Jul 03 17:15:48 CST 2014
     */
    private Integer level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cameraman.remark
     *
     * @mbggenerated Thu Jul 03 17:15:48 CST 2014
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cameraman.price
     *
     * @mbggenerated Thu Jul 03 17:15:48 CST 2014
     */
    private Integer price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cameraman.del
     *
     * @mbggenerated Thu Jul 03 17:15:48 CST 2014
     */
    private Integer del;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cameraman.id
     *
     * @return the value of cameraman.id
     *
     * @mbggenerated Thu Jul 03 17:15:48 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cameraman.id
     *
     * @param id the value for cameraman.id
     *
     * @mbggenerated Thu Jul 03 17:15:48 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cameraman.name
     *
     * @return the value of cameraman.name
     *
     * @mbggenerated Thu Jul 03 17:15:48 CST 2014
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cameraman.name
     *
     * @param name the value for cameraman.name
     *
     * @mbggenerated Thu Jul 03 17:15:48 CST 2014
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cameraman.tel
     *
     * @return the value of cameraman.tel
     *
     * @mbggenerated Thu Jul 03 17:15:48 CST 2014
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cameraman.tel
     *
     * @param tel the value for cameraman.tel
     *
     * @mbggenerated Thu Jul 03 17:15:48 CST 2014
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cameraman.mail
     *
     * @return the value of cameraman.mail
     *
     * @mbggenerated Thu Jul 03 17:15:48 CST 2014
     */
    public String getMail() {
        return mail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cameraman.mail
     *
     * @param mail the value for cameraman.mail
     *
     * @mbggenerated Thu Jul 03 17:15:48 CST 2014
     */
    public void setMail(String mail) {
        this.mail = mail == null ? null : mail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cameraman.camera_type
     *
     * @return the value of cameraman.camera_type
     *
     * @mbggenerated Thu Jul 03 17:15:48 CST 2014
     */
    public String getCameraType() {
        return cameraType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cameraman.camera_type
     *
     * @param cameraType the value for cameraman.camera_type
     *
     * @mbggenerated Thu Jul 03 17:15:48 CST 2014
     */
    public void setCameraType(String cameraType) {
        this.cameraType = cameraType == null ? null : cameraType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cameraman.level
     *
     * @return the value of cameraman.level
     *
     * @mbggenerated Thu Jul 03 17:15:48 CST 2014
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cameraman.level
     *
     * @param level the value for cameraman.level
     *
     * @mbggenerated Thu Jul 03 17:15:48 CST 2014
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cameraman.remark
     *
     * @return the value of cameraman.remark
     *
     * @mbggenerated Thu Jul 03 17:15:48 CST 2014
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cameraman.remark
     *
     * @param remark the value for cameraman.remark
     *
     * @mbggenerated Thu Jul 03 17:15:48 CST 2014
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cameraman.price
     *
     * @return the value of cameraman.price
     *
     * @mbggenerated Thu Jul 03 17:15:48 CST 2014
     */
    public Integer getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cameraman.price
     *
     * @param price the value for cameraman.price
     *
     * @mbggenerated Thu Jul 03 17:15:48 CST 2014
     */
    public void setPrice(Integer price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cameraman.del
     *
     * @return the value of cameraman.del
     *
     * @mbggenerated Thu Jul 03 17:15:48 CST 2014
     */
    public Integer getDel() {
        return del;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cameraman.del
     *
     * @param del the value for cameraman.del
     *
     * @mbggenerated Thu Jul 03 17:15:48 CST 2014
     */
    public void setDel(Integer del) {
        this.del = del;
    }
}