package com.wedding.john.oa.bean;

import java.util.Date;

import org.codehaus.jackson.map.annotate.JsonSerialize;
@JsonSerialize(include=JsonSerialize.Inclusion.NON_NULL)
public class Order {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.no
     *
     * @mbggenerated
     */
    private String no;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.company_id
     *
     * @mbggenerated
     */
    private Integer companyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.start_date
     *
     * @mbggenerated
     */
    private Date startDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.end_date
     *
     * @mbggenerated
     */
    private Date endDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.price
     *
     * @mbggenerated
     */
    private Integer price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.unit
     *
     * @mbggenerated
     */
    private Integer unit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.hotal_name
     *
     * @mbggenerated
     */
    private String hotalName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.hotal_address
     *
     * @mbggenerated
     */
    private String hotalAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.boy_name
     *
     * @mbggenerated
     */
    private String boyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.boy_tel
     *
     * @mbggenerated
     */
    private String boyTel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.girl_name
     *
     * @mbggenerated
     */
    private String girlName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.girl_tel
     *
     * @mbggenerated
     */
    private String girlTel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.pay_type
     *
     * @mbggenerated
     */
    private Integer payType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.needman
     *
     * @mbggenerated
     */
    private String needman;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.create_user
     *
     * @mbggenerated
     */
    private Integer createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.modify_user
     *
     * @mbggenerated
     */
    private Integer modifyUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.modify_time
     *
     * @mbggenerated
     */
    private Date modifyTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.id
     *
     * @return the value of order.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.id
     *
     * @param id the value for order.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.no
     *
     * @return the value of order.no
     *
     * @mbggenerated
     */
    public String getNo() {
        return no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.no
     *
     * @param no the value for order.no
     *
     * @mbggenerated
     */
    public void setNo(String no) {
        this.no = no == null ? null : no.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.company_id
     *
     * @return the value of order.company_id
     *
     * @mbggenerated
     */
    public Integer getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.company_id
     *
     * @param companyId the value for order.company_id
     *
     * @mbggenerated
     */
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.start_date
     *
     * @return the value of order.start_date
     *
     * @mbggenerated
     */
    public Date getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.start_date
     *
     * @param startDate the value for order.start_date
     *
     * @mbggenerated
     */
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.end_date
     *
     * @return the value of order.end_date
     *
     * @mbggenerated
     */
    public Date getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.end_date
     *
     * @param endDate the value for order.end_date
     *
     * @mbggenerated
     */
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.price
     *
     * @return the value of order.price
     *
     * @mbggenerated
     */
    public Integer getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.price
     *
     * @param price the value for order.price
     *
     * @mbggenerated
     */
    public void setPrice(Integer price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.unit
     *
     * @return the value of order.unit
     *
     * @mbggenerated
     */
    public Integer getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.unit
     *
     * @param unit the value for order.unit
     *
     * @mbggenerated
     */
    public void setUnit(Integer unit) {
        this.unit = unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.hotal_name
     *
     * @return the value of order.hotal_name
     *
     * @mbggenerated
     */
    public String getHotalName() {
        return hotalName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.hotal_name
     *
     * @param hotalName the value for order.hotal_name
     *
     * @mbggenerated
     */
    public void setHotalName(String hotalName) {
        this.hotalName = hotalName == null ? null : hotalName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.hotal_address
     *
     * @return the value of order.hotal_address
     *
     * @mbggenerated
     */
    public String getHotalAddress() {
        return hotalAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.hotal_address
     *
     * @param hotalAddress the value for order.hotal_address
     *
     * @mbggenerated
     */
    public void setHotalAddress(String hotalAddress) {
        this.hotalAddress = hotalAddress == null ? null : hotalAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.boy_name
     *
     * @return the value of order.boy_name
     *
     * @mbggenerated
     */
    public String getBoyName() {
        return boyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.boy_name
     *
     * @param boyName the value for order.boy_name
     *
     * @mbggenerated
     */
    public void setBoyName(String boyName) {
        this.boyName = boyName == null ? null : boyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.boy_tel
     *
     * @return the value of order.boy_tel
     *
     * @mbggenerated
     */
    public String getBoyTel() {
        return boyTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.boy_tel
     *
     * @param boyTel the value for order.boy_tel
     *
     * @mbggenerated
     */
    public void setBoyTel(String boyTel) {
        this.boyTel = boyTel == null ? null : boyTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.girl_name
     *
     * @return the value of order.girl_name
     *
     * @mbggenerated
     */
    public String getGirlName() {
        return girlName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.girl_name
     *
     * @param girlName the value for order.girl_name
     *
     * @mbggenerated
     */
    public void setGirlName(String girlName) {
        this.girlName = girlName == null ? null : girlName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.girl_tel
     *
     * @return the value of order.girl_tel
     *
     * @mbggenerated
     */
    public String getGirlTel() {
        return girlTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.girl_tel
     *
     * @param girlTel the value for order.girl_tel
     *
     * @mbggenerated
     */
    public void setGirlTel(String girlTel) {
        this.girlTel = girlTel == null ? null : girlTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.pay_type
     *
     * @return the value of order.pay_type
     *
     * @mbggenerated
     */
    public Integer getPayType() {
        return payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.pay_type
     *
     * @param payType the value for order.pay_type
     *
     * @mbggenerated
     */
    public void setPayType(Integer payType) {
        this.payType = payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.needman
     *
     * @return the value of order.needman
     *
     * @mbggenerated
     */
    public String getNeedman() {
        return needman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.needman
     *
     * @param needman the value for order.needman
     *
     * @mbggenerated
     */
    public void setNeedman(String needman) {
        this.needman = needman == null ? null : needman.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.create_user
     *
     * @return the value of order.create_user
     *
     * @mbggenerated
     */
    public Integer getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.create_user
     *
     * @param createUser the value for order.create_user
     *
     * @mbggenerated
     */
    public void setCreateUser(Integer createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.modify_user
     *
     * @return the value of order.modify_user
     *
     * @mbggenerated
     */
    public Integer getModifyUser() {
        return modifyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.modify_user
     *
     * @param modifyUser the value for order.modify_user
     *
     * @mbggenerated
     */
    public void setModifyUser(Integer modifyUser) {
        this.modifyUser = modifyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.create_time
     *
     * @return the value of order.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.create_time
     *
     * @param createTime the value for order.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.modify_time
     *
     * @return the value of order.modify_time
     *
     * @mbggenerated
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.modify_time
     *
     * @param modifyTime the value for order.modify_time
     *
     * @mbggenerated
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }
}