package com.wedding.john.oa.bean;

import java.util.Date;

public class OrderInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.order_no
     *
     * @mbggenerated
     */
    private String orderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.company_id
     *
     * @mbggenerated
     */
    private Integer companyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.start_date
     *
     * @mbggenerated
     */
    private Date startDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.end_date
     *
     * @mbggenerated
     */
    private Date endDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.price
     *
     * @mbggenerated
     */
    private Integer price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.unit
     *
     * @mbggenerated
     */
    private Integer unit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.over_pirce
     *
     * @mbggenerated
     */
    private Integer overPirce;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.hotal_name
     *
     * @mbggenerated
     */
    private String hotalName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.hotal_address
     *
     * @mbggenerated
     */
    private String hotalAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.boy_name
     *
     * @mbggenerated
     */
    private String boyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.boy_tel
     *
     * @mbggenerated
     */
    private String boyTel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.boy_address
     *
     * @mbggenerated
     */
    private String boyAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.girl_name
     *
     * @mbggenerated
     */
    private String girlName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.girl_tel
     *
     * @mbggenerated
     */
    private String girlTel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.girl_address
     *
     * @mbggenerated
     */
    private String girlAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.pay_type
     *
     * @mbggenerated
     */
    private Integer payType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.over_pay_type
     *
     * @mbggenerated
     */
    private Integer overPayType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.needman
     *
     * @mbggenerated
     */
    private String needman;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.contact_man
     *
     * @mbggenerated
     */
    private String contactMan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.create_user
     *
     * @mbggenerated
     */
    private Integer createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.modify_user
     *
     * @mbggenerated
     */
    private Integer modifyUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.modify_time
     *
     * @mbggenerated
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.id
     *
     * @return the value of order_info.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.id
     *
     * @param id the value for order_info.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.order_no
     *
     * @return the value of order_info.order_no
     *
     * @mbggenerated
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.order_no
     *
     * @param orderNo the value for order_info.order_no
     *
     * @mbggenerated
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo == null ? null : orderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.company_id
     *
     * @return the value of order_info.company_id
     *
     * @mbggenerated
     */
    public Integer getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.company_id
     *
     * @param companyId the value for order_info.company_id
     *
     * @mbggenerated
     */
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.start_date
     *
     * @return the value of order_info.start_date
     *
     * @mbggenerated
     */
    public Date getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.start_date
     *
     * @param startDate the value for order_info.start_date
     *
     * @mbggenerated
     */
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.end_date
     *
     * @return the value of order_info.end_date
     *
     * @mbggenerated
     */
    public Date getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.end_date
     *
     * @param endDate the value for order_info.end_date
     *
     * @mbggenerated
     */
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.price
     *
     * @return the value of order_info.price
     *
     * @mbggenerated
     */
    public Integer getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.price
     *
     * @param price the value for order_info.price
     *
     * @mbggenerated
     */
    public void setPrice(Integer price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.unit
     *
     * @return the value of order_info.unit
     *
     * @mbggenerated
     */
    public Integer getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.unit
     *
     * @param unit the value for order_info.unit
     *
     * @mbggenerated
     */
    public void setUnit(Integer unit) {
        this.unit = unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.over_pirce
     *
     * @return the value of order_info.over_pirce
     *
     * @mbggenerated
     */
    public Integer getOverPirce() {
        return overPirce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.over_pirce
     *
     * @param overPirce the value for order_info.over_pirce
     *
     * @mbggenerated
     */
    public void setOverPirce(Integer overPirce) {
        this.overPirce = overPirce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.hotal_name
     *
     * @return the value of order_info.hotal_name
     *
     * @mbggenerated
     */
    public String getHotalName() {
        return hotalName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.hotal_name
     *
     * @param hotalName the value for order_info.hotal_name
     *
     * @mbggenerated
     */
    public void setHotalName(String hotalName) {
        this.hotalName = hotalName == null ? null : hotalName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.hotal_address
     *
     * @return the value of order_info.hotal_address
     *
     * @mbggenerated
     */
    public String getHotalAddress() {
        return hotalAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.hotal_address
     *
     * @param hotalAddress the value for order_info.hotal_address
     *
     * @mbggenerated
     */
    public void setHotalAddress(String hotalAddress) {
        this.hotalAddress = hotalAddress == null ? null : hotalAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.boy_name
     *
     * @return the value of order_info.boy_name
     *
     * @mbggenerated
     */
    public String getBoyName() {
        return boyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.boy_name
     *
     * @param boyName the value for order_info.boy_name
     *
     * @mbggenerated
     */
    public void setBoyName(String boyName) {
        this.boyName = boyName == null ? null : boyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.boy_tel
     *
     * @return the value of order_info.boy_tel
     *
     * @mbggenerated
     */
    public String getBoyTel() {
        return boyTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.boy_tel
     *
     * @param boyTel the value for order_info.boy_tel
     *
     * @mbggenerated
     */
    public void setBoyTel(String boyTel) {
        this.boyTel = boyTel == null ? null : boyTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.boy_address
     *
     * @return the value of order_info.boy_address
     *
     * @mbggenerated
     */
    public String getBoyAddress() {
        return boyAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.boy_address
     *
     * @param boyAddress the value for order_info.boy_address
     *
     * @mbggenerated
     */
    public void setBoyAddress(String boyAddress) {
        this.boyAddress = boyAddress == null ? null : boyAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.girl_name
     *
     * @return the value of order_info.girl_name
     *
     * @mbggenerated
     */
    public String getGirlName() {
        return girlName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.girl_name
     *
     * @param girlName the value for order_info.girl_name
     *
     * @mbggenerated
     */
    public void setGirlName(String girlName) {
        this.girlName = girlName == null ? null : girlName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.girl_tel
     *
     * @return the value of order_info.girl_tel
     *
     * @mbggenerated
     */
    public String getGirlTel() {
        return girlTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.girl_tel
     *
     * @param girlTel the value for order_info.girl_tel
     *
     * @mbggenerated
     */
    public void setGirlTel(String girlTel) {
        this.girlTel = girlTel == null ? null : girlTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.girl_address
     *
     * @return the value of order_info.girl_address
     *
     * @mbggenerated
     */
    public String getGirlAddress() {
        return girlAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.girl_address
     *
     * @param girlAddress the value for order_info.girl_address
     *
     * @mbggenerated
     */
    public void setGirlAddress(String girlAddress) {
        this.girlAddress = girlAddress == null ? null : girlAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.pay_type
     *
     * @return the value of order_info.pay_type
     *
     * @mbggenerated
     */
    public Integer getPayType() {
        return payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.pay_type
     *
     * @param payType the value for order_info.pay_type
     *
     * @mbggenerated
     */
    public void setPayType(Integer payType) {
        this.payType = payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.over_pay_type
     *
     * @return the value of order_info.over_pay_type
     *
     * @mbggenerated
     */
    public Integer getOverPayType() {
        return overPayType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.over_pay_type
     *
     * @param overPayType the value for order_info.over_pay_type
     *
     * @mbggenerated
     */
    public void setOverPayType(Integer overPayType) {
        this.overPayType = overPayType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.needman
     *
     * @return the value of order_info.needman
     *
     * @mbggenerated
     */
    public String getNeedman() {
        return needman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.needman
     *
     * @param needman the value for order_info.needman
     *
     * @mbggenerated
     */
    public void setNeedman(String needman) {
        this.needman = needman == null ? null : needman.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.contact_man
     *
     * @return the value of order_info.contact_man
     *
     * @mbggenerated
     */
    public String getContactMan() {
        return contactMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.contact_man
     *
     * @param contactMan the value for order_info.contact_man
     *
     * @mbggenerated
     */
    public void setContactMan(String contactMan) {
        this.contactMan = contactMan == null ? null : contactMan.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.create_user
     *
     * @return the value of order_info.create_user
     *
     * @mbggenerated
     */
    public Integer getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.create_user
     *
     * @param createUser the value for order_info.create_user
     *
     * @mbggenerated
     */
    public void setCreateUser(Integer createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.modify_user
     *
     * @return the value of order_info.modify_user
     *
     * @mbggenerated
     */
    public Integer getModifyUser() {
        return modifyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.modify_user
     *
     * @param modifyUser the value for order_info.modify_user
     *
     * @mbggenerated
     */
    public void setModifyUser(Integer modifyUser) {
        this.modifyUser = modifyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.create_time
     *
     * @return the value of order_info.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.create_time
     *
     * @param createTime the value for order_info.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.modify_time
     *
     * @return the value of order_info.modify_time
     *
     * @mbggenerated
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.modify_time
     *
     * @param modifyTime the value for order_info.modify_time
     *
     * @mbggenerated
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.status
     *
     * @return the value of order_info.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.status
     *
     * @param status the value for order_info.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.remark
     *
     * @return the value of order_info.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.remark
     *
     * @param remark the value for order_info.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}