package com.wedding.john.oa.bean;

import java.util.Date;

public class ScheduleKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.cameraman_id
     *
     * @mbggenerated
     */
    private Integer cameramanId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.empty_date
     *
     * @mbggenerated
     */
    private Date emptyDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.cameraman_id
     *
     * @return the value of schedule.cameraman_id
     *
     * @mbggenerated
     */
    public Integer getCameramanId() {
        return cameramanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.cameraman_id
     *
     * @param cameramanId the value for schedule.cameraman_id
     *
     * @mbggenerated
     */
    public void setCameramanId(Integer cameramanId) {
        this.cameramanId = cameramanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.empty_date
     *
     * @return the value of schedule.empty_date
     *
     * @mbggenerated
     */
    public Date getEmptyDate() {
        return emptyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.empty_date
     *
     * @param emptyDate the value for schedule.empty_date
     *
     * @mbggenerated
     */
    public void setEmptyDate(Date emptyDate) {
        this.emptyDate = emptyDate;
    }
}