package com.wedding.john.oa.bean;

import java.util.Date;

import org.codehaus.jackson.map.annotate.JsonSerialize;
@JsonSerialize(include=JsonSerialize.Inclusion.NON_NULL)
public class Schedule extends ScheduleKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.is_use
     *
     * @mbggenerated
     */
    private Integer isUse;
    
    private Date busyDate;


	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.is_use
     *
     * @return the value of schedule.is_use
     *
     * @mbggenerated
     */
    public Integer getIsUse() {
        return isUse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.is_use
     *
     * @param isUse the value for schedule.is_use
     *
     * @mbggenerated
     */
    public void setIsUse(Integer isUse) {
        this.isUse = isUse;
    }

	/**
	 * @return the busyDate
	 */
	public Date getBusyDate() {
		return busyDate;
	}

	/**
	 * @param busyDate the busyDate to set
	 */
	public void setBusyDate(Date busyDate) {
		this.busyDate = busyDate;
	}
    
}