package com.wedding.john.oa.bean;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class ScheduleExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table schedule
     *
     * @mbggenerated Thu Jul 03 17:15:48 CST 2014
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table schedule
     *
     * @mbggenerated Thu Jul 03 17:15:48 CST 2014
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table schedule
     *
     * @mbggenerated Thu Jul 03 17:15:48 CST 2014
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule
     *
     * @mbggenerated Thu Jul 03 17:15:48 CST 2014
     */
    public ScheduleExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule
     *
     * @mbggenerated Thu Jul 03 17:15:48 CST 2014
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule
     *
     * @mbggenerated Thu Jul 03 17:15:48 CST 2014
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule
     *
     * @mbggenerated Thu Jul 03 17:15:48 CST 2014
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule
     *
     * @mbggenerated Thu Jul 03 17:15:48 CST 2014
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule
     *
     * @mbggenerated Thu Jul 03 17:15:48 CST 2014
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule
     *
     * @mbggenerated Thu Jul 03 17:15:48 CST 2014
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule
     *
     * @mbggenerated Thu Jul 03 17:15:48 CST 2014
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule
     *
     * @mbggenerated Thu Jul 03 17:15:48 CST 2014
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule
     *
     * @mbggenerated Thu Jul 03 17:15:48 CST 2014
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule
     *
     * @mbggenerated Thu Jul 03 17:15:48 CST 2014
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table schedule
     *
     * @mbggenerated Thu Jul 03 17:15:48 CST 2014
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andCameramanIdIsNull() {
            addCriterion("cameraman_id is null");
            return (Criteria) this;
        }

        public Criteria andCameramanIdIsNotNull() {
            addCriterion("cameraman_id is not null");
            return (Criteria) this;
        }

        public Criteria andCameramanIdEqualTo(Integer value) {
            addCriterion("cameraman_id =", value, "cameramanId");
            return (Criteria) this;
        }

        public Criteria andCameramanIdNotEqualTo(Integer value) {
            addCriterion("cameraman_id <>", value, "cameramanId");
            return (Criteria) this;
        }

        public Criteria andCameramanIdGreaterThan(Integer value) {
            addCriterion("cameraman_id >", value, "cameramanId");
            return (Criteria) this;
        }

        public Criteria andCameramanIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("cameraman_id >=", value, "cameramanId");
            return (Criteria) this;
        }

        public Criteria andCameramanIdLessThan(Integer value) {
            addCriterion("cameraman_id <", value, "cameramanId");
            return (Criteria) this;
        }

        public Criteria andCameramanIdLessThanOrEqualTo(Integer value) {
            addCriterion("cameraman_id <=", value, "cameramanId");
            return (Criteria) this;
        }

        public Criteria andCameramanIdIn(List<Integer> values) {
            addCriterion("cameraman_id in", values, "cameramanId");
            return (Criteria) this;
        }

        public Criteria andCameramanIdNotIn(List<Integer> values) {
            addCriterion("cameraman_id not in", values, "cameramanId");
            return (Criteria) this;
        }

        public Criteria andCameramanIdBetween(Integer value1, Integer value2) {
            addCriterion("cameraman_id between", value1, value2, "cameramanId");
            return (Criteria) this;
        }

        public Criteria andCameramanIdNotBetween(Integer value1, Integer value2) {
            addCriterion("cameraman_id not between", value1, value2, "cameramanId");
            return (Criteria) this;
        }

        public Criteria andBusydateIsNull() {
            addCriterion("busydate is null");
            return (Criteria) this;
        }

        public Criteria andBusydateIsNotNull() {
            addCriterion("busydate is not null");
            return (Criteria) this;
        }

        public Criteria andBusydateEqualTo(Date value) {
            addCriterionForJDBCDate("busydate =", value, "busydate");
            return (Criteria) this;
        }

        public Criteria andBusydateNotEqualTo(Date value) {
            addCriterionForJDBCDate("busydate <>", value, "busydate");
            return (Criteria) this;
        }

        public Criteria andBusydateGreaterThan(Date value) {
            addCriterionForJDBCDate("busydate >", value, "busydate");
            return (Criteria) this;
        }

        public Criteria andBusydateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("busydate >=", value, "busydate");
            return (Criteria) this;
        }

        public Criteria andBusydateLessThan(Date value) {
            addCriterionForJDBCDate("busydate <", value, "busydate");
            return (Criteria) this;
        }

        public Criteria andBusydateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("busydate <=", value, "busydate");
            return (Criteria) this;
        }

        public Criteria andBusydateIn(List<Date> values) {
            addCriterionForJDBCDate("busydate in", values, "busydate");
            return (Criteria) this;
        }

        public Criteria andBusydateNotIn(List<Date> values) {
            addCriterionForJDBCDate("busydate not in", values, "busydate");
            return (Criteria) this;
        }

        public Criteria andBusydateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("busydate between", value1, value2, "busydate");
            return (Criteria) this;
        }

        public Criteria andBusydateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("busydate not between", value1, value2, "busydate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table schedule
     *
     * @mbggenerated do_not_delete_during_merge Thu Jul 03 17:15:48 CST 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table schedule
     *
     * @mbggenerated Thu Jul 03 17:15:48 CST 2014
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}