package com.wedding.john.oa.bean;

public class SkillInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skill_info.userId
     *
     * @mbggenerated
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skill_info.skillId
     *
     * @mbggenerated
     */
    private Integer skillid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skill_info.userId
     *
     * @return the value of skill_info.userId
     *
     * @mbggenerated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skill_info.userId
     *
     * @param userid the value for skill_info.userId
     *
     * @mbggenerated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skill_info.skillId
     *
     * @return the value of skill_info.skillId
     *
     * @mbggenerated
     */
    public Integer getSkillid() {
        return skillid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skill_info.skillId
     *
     * @param skillid the value for skill_info.skillId
     *
     * @mbggenerated
     */
    public void setSkillid(Integer skillid) {
        this.skillid = skillid;
    }
}