package com.wedding.john.oa.bean;

public class Skill {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skill.id
     *
     * @mbggenerated Thu Jul 03 17:15:48 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skill.name
     *
     * @mbggenerated Thu Jul 03 17:15:48 CST 2014
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skill.id
     *
     * @return the value of skill.id
     *
     * @mbggenerated Thu Jul 03 17:15:48 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skill.id
     *
     * @param id the value for skill.id
     *
     * @mbggenerated Thu Jul 03 17:15:48 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skill.name
     *
     * @return the value of skill.name
     *
     * @mbggenerated Thu Jul 03 17:15:48 CST 2014
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skill.name
     *
     * @param name the value for skill.name
     *
     * @mbggenerated Thu Jul 03 17:15:48 CST 2014
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}