package com.wedding.john.oa.dao;

import com.wedding.john.oa.bean.Cameraman;
import com.wedding.john.oa.bean.CameramanExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CameramanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cameraman
     *
     * @mbggenerated Thu Jul 03 17:15:48 CST 2014
     */
    int countByExample(CameramanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cameraman
     *
     * @mbggenerated Thu Jul 03 17:15:48 CST 2014
     */
    int deleteByExample(CameramanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cameraman
     *
     * @mbggenerated Thu Jul 03 17:15:48 CST 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cameraman
     *
     * @mbggenerated Thu Jul 03 17:15:48 CST 2014
     */
    int insert(Cameraman record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cameraman
     *
     * @mbggenerated Thu Jul 03 17:15:48 CST 2014
     */
    int insertSelective(Cameraman record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cameraman
     *
     * @mbggenerated Thu Jul 03 17:15:48 CST 2014
     */
    List<Cameraman> selectByExample(CameramanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cameraman
     *
     * @mbggenerated Thu Jul 03 17:15:48 CST 2014
     */
    Cameraman selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cameraman
     *
     * @mbggenerated Thu Jul 03 17:15:48 CST 2014
     */
    int updateByExampleSelective(@Param("record") Cameraman record, @Param("example") CameramanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cameraman
     *
     * @mbggenerated Thu Jul 03 17:15:48 CST 2014
     */
    int updateByExample(@Param("record") Cameraman record, @Param("example") CameramanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cameraman
     *
     * @mbggenerated Thu Jul 03 17:15:48 CST 2014
     */
    int updateByPrimaryKeySelective(Cameraman record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cameraman
     *
     * @mbggenerated Thu Jul 03 17:15:48 CST 2014
     */
    int updateByPrimaryKey(Cameraman record);
}