package com.wedding.john.oa.dao;

import java.util.Date;
import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.wedding.john.oa.bean.MyOrder;
import com.wedding.john.oa.bean.OrderInfo;
import com.wedding.john.oa.bean.OrderInfoExample;

public interface OrderInfoMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table order_info
	 * 
	 * @mbggenerated
	 */
	int countByExample(OrderInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table order_info
	 * 
	 * @mbggenerated
	 */
	int deleteByExample(OrderInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table order_info
	 * 
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table order_info
	 * 
	 * @mbggenerated
	 */
	int insert(OrderInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table order_info
	 * 
	 * @mbggenerated
	 */
	int insertSelective(OrderInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table order_info
	 * 
	 * @mbggenerated
	 */
	List<OrderInfo> selectByExample(OrderInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table order_info
	 * 
	 * @mbggenerated
	 */
	OrderInfo selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table order_info
	 * 
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") OrderInfo record,
			@Param("example") OrderInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table order_info
	 * 
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") OrderInfo record,
			@Param("example") OrderInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table order_info
	 * 
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(OrderInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table order_info
	 * 
	 * @mbggenerated
	 */
	int updateByPrimaryKey(OrderInfo record);

	/**
	 * 我的未拍订单
	 * 
	 * @param startDate
	 * @param userId
	 * @return
	 */
	List<MyOrder> selectMyFutureOrders(@Param("userId") Integer userId,
			@Param("startDate") Date startDate);

	/**
	 * 我的历史订单
	 * 
	 * @param startDate
	 * @param userId
	 * @return
	 */
	List<MyOrder> selectMyHistoryOrders(@Param("userId") Integer userId,
			@Param("startDate") Date startDate, @Param("endDate") Date endDate);
}