package com.wedding.john.oa.dao;

import com.wedding.john.oa.bean.SkillInfo;
import com.wedding.john.oa.bean.SkillInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SkillInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skill_info
     *
     * @mbggenerated
     */
    int countByExample(SkillInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skill_info
     *
     * @mbggenerated
     */
    int deleteByExample(SkillInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skill_info
     *
     * @mbggenerated
     */
    int insert(SkillInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skill_info
     *
     * @mbggenerated
     */
    int insertSelective(SkillInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skill_info
     *
     * @mbggenerated
     */
    List<SkillInfo> selectByExample(SkillInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skill_info
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SkillInfo record, @Param("example") SkillInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skill_info
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SkillInfo record, @Param("example") SkillInfoExample example);
    
	/**
	 * 按工种查找
	 * 
	 * @param example
	 * @return
	 */
	List<SkillInfo> selectBySkillId(SkillInfoExample example);
}